name: builder

on: [push, pull_request]

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: check binary
      run: ls | grep "201yams"
    - name: run tests
      run: ./test.sh